export const TICKETS_LOAD = 'TICKETS_LOAD'
export const GET_SEARCH_ID = 'GET_SEARCH_ID'
export const GET_TICKETS = 'GET_TICKETS'
export const GET_ERROR = 'GET_ERROR'
export const FILTER_CHANGE = 'FILTER_CHANGE'
export const CHANGE_SORT = 'CHANGE_SORT'
